---
version: '2'
services:
  redis:
    image: bitnami/redis:latest
    hostname: redis
    container_name: redis
    ports:
    - 6379:6379
    environment:
      REDIS_PASSWORD: test
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379:0:test
    ports:
    - 8083:8081
